### ISSUE TITLE
OpenVPN 3 Autload is being deprecated

### ISSUE THREAD

**Issue by dsommers** [dbritto-dev/openvpn3-action#1]
Hi,

I'm the upstream maintainer of the [OpenVPN 3 Linux](https://github.com/OpenVPN/openvpn3-linux) project and I just stumbled across this project.  I just wanted to give a heads up that the `openvpn3-autoload` approach is being deprecated and will at some point be removed in a later release.

The approach to use now is:

* Import the configuration profile using

      $ openvpn3 config-import --persistent --config ${CONFIG_FILE} --name ${CONFIG_NAME}

* Start the VPN session using either:

      # systemctl enable --now openvpn3-session@${CONFIG_NAME}

   **or**

      # openvpn3 session-start --config ${CONFIG_NAME}

  The former will automatically start the connecting on each boot, the latter needs to be run each time you want to start the VPN connection.

The `${CONFIG_FILE}` itself may now also contain `<auth-user-pass>...</auth-user-pass>` tags if username/password auth is required; this will be further hardened with support for keyring services and such.

If there are additional settings which was configured via the `.autoload` file, they can now be set properly via `openvpn3 config-manage --config ${CONFIG_NAME}`.  See the [`openvpn3-config-manage`(1)](https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn3-config-manage.1.rst) man page for details

**Comment by dbritto-dev** [comment]
@dsommers cool, thanks a lot for pointing out that. I'll work on updating this gh action to follow the new approach.

**Comment by dsommers** [comment]
If it makes it easier for you, OpenVPN 3 Linux is based on D-Bus so you can manage it directly this way.  It also ships with an `openvpn3` Python 3 module, where you can do all the things you do with the `openvpn3` command line tool.

A few examples:
* https://github.com/OpenVPN/openvpn3-linux/blob/master/src/tests/python/configimport.py
* https://github.com/OpenVPN/openvpn3-linux/blob/master/src/tests/python/start-tunnel2.py

**Comment by dbritto-dev** [comment]
@dsommers thanks for the docs. Actually, for this project I want to keep it simple using bash and exposing a way to run any command, so people can use that for simple and complex things.
